# Generated by Django 4.0.1 on 2022-01-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('roles', models.CharField(max_length=256)),
                ('biography', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('year', models.DateField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.CharField(max_length=256)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='blackarchives.director')),
            ],
        ),
    ]
