# Generated by Django 4.0.1 on 2022-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackarchives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
        migrations.AddField(
            model_name='film',
            name='release',
            field=models.IntegerField(null=True),
        ),
    ]
