# Generated by Django 4.0.1 on 2022-01-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackarchives', '0002_remove_film_year_film_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='release',
        ),
    ]
