# Generated by Django 4.0.1 on 2022-01-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackarchives', '0003_remove_film_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='release',
            field=models.IntegerField(null=True),
        ),
    ]
