# Generated by Django 4.0.1 on 2022-01-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackarchives', '0004_film_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='films', to='blackarchives.director'),
        ),
    ]
